### ISSUE TITLE
Infinite scroll does trigger fetching next bunch of date on too fast scroll

### ISSUE THREAD

**Issue by ibabchanik** [orizens/angular2-infinite-scroll#100]
Infinite scroll does trigger fetching next bunch of date on too fast scroll. 
Scroll area is located in container. When do fast scroll to end of scroll area and go out of container -  scroll event doesn't trigger. To get the event you need to scroll up.

**Comment by orizens** [comment]
hi @ibabchanik 
currently, to fix it, try setting the "infiniteScrollDistance" to 2 or 1

**Comment by ibabchanik** [comment]
I have tried it, unfortunately it's doesn't help

**Comment by Kelthan** [comment]
hi,
I'm facing the same issue. If I scroll too fast, I can reach the bottom of the page and scroll event is not triggered even with a "infiniteScrollDistance" set to 1.
Maybe it could be possible to implement something to trigger scroll event when we reach the bottom of the page ?

**Comment by orizens** [comment]
hi @Kelthan @ibabchanik 
set the "[infiniteScrollThrottle]" to a low value - 10-50 - and it should solves most "fast" scrolling issues.

**Comment by orizens** [comment]
for future reference: 
a possible solution is have a timeout function with "throttle" ms that will check if scrolled to bottom, and when true, will emit an event.

**Comment by orizens** [comment]
new version (0.2.7) fixes this behavior
8543ef7344a64ceaf7617d1953f98adae3595092
