### ISSUE TITLE
AOT compatibility

### ISSUE THREAD

**Issue by dmk12** [orizens/angular2-infinite-scroll#101]
Getting the following error in v0.2.7 with AOT:
Error: 'InfiniteScrollModule' is not exported by node_modules/angular2-infinite-scroll/angular2-infinite-scroll.js (imported by src/app/app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

Thought this was fixed in https://github.com/orizens/angular2-infinite-scroll/pull/84, after being logged in https://github.com/orizens/angular2-infinite-scroll/issues/77.
Is https://github.com/orizens/angular2-infinite-scroll/issues/77 definitely fixed?

**Comment by xalexslx** [comment]
I'm having the same issue.

**Comment by EgorBurykin** [comment]
Same here pointed in #82

**Comment by EgorBurykin** [comment]
I guess it's because of 'export * from ...' in main file. I made it work in project like that by changing 'export * from ...' to 'export {Name1, Name2} from ...'. After that my transplited cjs module have got exports recognizable by rollup.

**Comment by orizens** [comment]
Thanks for the information @EgorBurykin 
@xalexslx @dmk12 
Please try beta version ```angular2-infinite-scroll@0.2.8-0``` before I move this package to the next patch version.
Please let me know if this version fixes the issue with AOT.

**Comment by xalexslx** [comment]
@orizens seems working now, thanks. Also thanks to @EgorBurykin for adding knowledge to ours.

**Comment by orizens** [comment]
@xalexslx thanks for the feedback.
I'll publish a new version soon.

**Comment by orizens** [comment]
fixed by 252ba10199f279366c00e69dfdddf36bd2e1adf1
