### ISSUE TITLE
onScroll (up and down) gets called infinite times

### ISSUE THREAD

**Issue by timschutter** [orizens/angular2-infinite-scroll#109]
Followed the example to implement code:
`                    <div class="conversation-container"
                       infinite-scroll
                       [infiniteScrollDistance]="1.2"
                       [infiniteScrollUpDistance]="1.2"
                       [infiniteScrollThrottle]="500"
                       (scrolled)="onScrollDown()"
                       (scrolledUp)="onScrollUp()">
`
`    public onScrollDown() {
      console.log('onScrollDown')
    }
    public onScrollUp() {
      console.log('onScrollUP')
    }
`
Using Chrome, press the down arrow once and I get a flood of onScrollDown & onScrollUp.
Tried to debug but am out of ideas.

**Comment by BallisticPain** [comment]
Try to lower the infiniteScrollDistance? Just a thought. I'm trying to figure this beast out too...

**Comment by timschutter** [comment]
One of my mistakes was my list was too short (because generating data wasn't easy).  Make your list > 100 to start with and it will help out the function.  After I completed my 'add data' code, it appears to work fine BUT it appears to be thrashing a lot.  At the top of the list, moving down, still getting onScrollDown callbacks.  Interestingly, not so much when scrolling up.

**Comment by dusthub** [comment]
yep, I had got the same trouble.

**Comment by orizens** [comment]
can you please share a plunkr that reproduce this issue?

**Comment by dusthub** [comment]
@orizens Whoops! my mistake, i had set the wrong container for "infinite-scroll" directive. Everything goes well now in my browser.

**Comment by orizens** [comment]
@timschutter can i close this issue?

**Comment by timschutter** [comment]
I'm moving on with this issue - it can be closed.  For the window scroll, I see some thrashing but our page will be changed soon to a fixed div in the window.  If I don't see some change in when the onScroll is called, I'll revisit and issue another item with a plunkr.  Thank
