### ISSUE TITLE
scrolled event is not firing properly

### ISSUE THREAD

**Issue by dheeraja00** [orizens/angular2-infinite-scroll#110]
Hi I am using it as you guys have described, and previously I was using 0.1.95 version which was working fine, but then I upgraded it & this is causing some issues. `scrolled` event is not being called every time I scroll, to make it work I need to scroll back to the top and then scroll to the bottom. Since I have given `infiniteScrollDistance = 2` it should be called on half way around of the page.

**Comment by orizens** [comment]
hi.
please install the latest v 0.0.3 - it seems to be working fine. if you still experience issues - please reopen this or create a new issue.
