### ISSUE TITLE
scrolling with two scrollers

### ISSUE THREAD

**Issue by ths126** [orizens/angular2-infinite-scroll#115]
If i have a div with scrolling and the containing window has a scrolling the onScroll function is invoked twice when the div scroll reaches its end and when the window scroll reaches its end.

**Comment by orizens** [comment]
hi @ths126 
please have a [look at this example](https://plnkr.co/edit/QnQOwE9SEapwJCCFII3L?p=preview) - the onScroll is triggered separately for each scroller
