### ISSUE TITLE
trying to get infinite scroll work with angular 2 and typescript

### ISSUE THREAD

**Issue by TanyaLi** [orizens/angular2-infinite-scroll#117]
hi, 

basically trying to get it working in this format (not using NgModule), but failed:
https://plnkr.co/edit/uWvSSTSBBsiFcA6S6S5M?p=preview

any suggestions or help would be greatly appreciated ! 

Regards,
Xiaohui Li

**Comment by orizens** [comment]
it seems like your demo lacks of the appropriate way to run ng2.
you have to use a module system.
please consult the demo links within the README.md.

**Comment by TanyaLi** [comment]
thanks for the reply, got it working locally, was my bad, sorry !
