### ISSUE TITLE
Why package not working with angular2 seed ? 

### ISSUE THREAD

**Issue by macdasi** [orizens/angular2-infinite-scroll#118]
I use https://github.com/mgechev/angular-seed 
Configured it in the 

this.addPackageBundles({
            name: 'angular2-infinite-scroll',
            path: 'node_modules/angular2-infinite-scroll/angular2-infinite-scroll.js'
        });

I've imported the module

still get error 

>  Uncaught (in promise): Error: Template parse errors:
Can't bind to 'scrollWindow' since it isn't a known property of 'div'. ("
      <div 
           (scrolled)="onScroll()"
           [ERROR ->][scrollWindow]="false">

 ... any idea why it's not working ?

**Comment by orizens** [comment]
yes - you should use "[scrollWindow]="false" with brackets.

**Comment by macdasi** [comment]
I use it 

```
<div  (scrolled)="onScroll()"
           [scrollWindow]="false">
```

**Comment by orizens** [comment]
@macdasi 
it's hard to tell - please consult the example - https://plnkr.co/edit/QnQOwE9SEapwJCCFII3L?p=preview

**Comment by macdasi** [comment]
I was missing the " infinite-scroll" directive on the element
