### ISSUE TITLE
Issue during unit test in Angular CLI

### ISSUE THREAD

**Issue by vsharma2266** [orizens/angular2-infinite-scroll#119]
I am having issues with infinte scrolling.
I am using `angular-cli": "1.0.0-beta.21` and `Angular 2.2.1`.

I am using infintescroll in the following manner:

`<div class="brick" infinite-scroll [infiniteScrollDistance]=".2" (scrolled)="onScrollDown()" [infiniteScrollThrottle]='0' [infiniteScrollDisabled]="disableScroll" (keyup)="0">`

I get this issue when i run jasmine/karma test:
`Can't bind to 'infiniteScrollDistance' since it isn't a known property of 'div'`

`Can't bind to 'infiniteScrollThrottle' since it isn't a known property of 'div'`

`Can't bind to 'infiniteScrollDisabled' since it isn't a known property of 'div'. ` 

If i use infinite scroll in the following manner: 
`<div class="brick" infinite-scroll infiniteScrollDistance=".2" (scrolled)="onScrollDown()" infiniteScrollThrottle='0' infiniteScrollDisabled="disableScroll" (keyup)="0">`

I do not get the error in unit test but `infiniteScrollDistance`, `infiniteScrollThrottle`, `infiniteScrollDisabled` do not work as intended. I believe they are just setting to their default values and are not being changed according to the values in the `div`

Please let me know what can i do to resolve this .

**Comment by orizens** [comment]
hi @vsharma2266 
something is wrong with the code, i.e - infiniteScrollDistance should be "2" without the "dot". 
please consult the example plunkr - https://plnkr.co/edit/DrEDetYnZkFxR7OWWrxS?p=preview

**Comment by vsharma2266** [comment]
Hi @orizens ,

Even if i use 1 or 2 in place of 0.2 for infiniteScrollDistance, i still get unit test failure.
`<div class="brick" infinite-scroll [infiniteScrollDistance]="1" (scrolled)="onScrollDown()" [infiniteScrollThrottle]='0' [infiniteScrollDisabled]="disableScroll" (keyup)="0">`

Just to be clear, infiniteScroll is working properly in the application. It is just that it is failing unit tests because of above mentioned reasons.

**Comment by orizens** [comment]
it seems like you don't import the infinitescroll module to your test.

**Comment by vsharma2266** [comment]
Somehow the following is working for me in the application and does not give me any issues in the unit tests.

`<div class="brick" infinite-scroll infiniteScrollDistance="0.2" (scrolled)="onScrollDown()" infiniteScrollThrottle="0">
`

BUT 

If i use `[infiniteScrollDisabled]="disableScroll" `, it breaks the unit test 
and if i use  `infiniteScrollDisabled="disableScroll"`, it breaks the infinite scroll in the application.
I am not able to use `infiniteScrollDisabled` in the application which i would like to. 
I do not see you using it in your demo apps as well.

Please advice.

**Comment by vsharma2266** [comment]
You are right. I did forget it in unit test.

Thanks a lot. It seems to be working correctly.
