### ISSUE TITLE
Scroll event triggered on navigation

### ISSUE THREAD

**Issue by renehamburger** [orizens/angular2-infinite-scroll#121]
This isn't a bug with this module, but I was wondering whether you've encountered this issue before and are aware of a work-around. When I navigate from a route/view which is scrolled down to another route/view, a scroll event is triggered. If the second view as an angular2-infinite-scroll handler attached, it will trigger even before the initial data is loaded, which may often lead to exceptions.

I tried setting the scroll position to 0 on NavigationStart (even outside of Angular's zone), but the scroll event is still triggered.

Apart from adding logic to each handler to check for the original data being loaded before requesting more (and apart from wrapping Zone.js functions), can you think of any other way to resolve this issue?

**Comment by orizens** [comment]
hi @renehamburger 
currently, you will have to handle this logic with NavigationStart event. 
A possible solution for this that we can checkout (currently i need to investigate more) is to check whether the component has been destroyed before emitting events.

**Comment by renehamburger** [comment]
Thanks for your feedback! If other users encounter the same issue, maybe it will be worth adding a work-around to this module.
