### ISSUE TITLE
I want to 

### ISSUE THREAD

**Issue by kgtkr** [orizens/angular2-infinite-scroll#122]
sorry. I have sent you an unfinished

subject:I want to get element index.

# example
![image](https://cloud.githubusercontent.com/assets/17868838/22972460/05b323e4-f3bd-11e6-92af-5919e25e1dee.png)
index value=5

Sorry I'm not good in English.

**Comment by orizens** [comment]
I apologize - i don't understand the question. i think it's related to a general angular subject.

**Comment by kgtkr** [comment]
japanese:
無限スクロール内部の要素にインデックスを付け、getIndexで現在のスクロール位置を取得、setIndexで特定要素までスクロールする機能が欲しいです
