### ISSUE TITLE
Is webpack supported?

### ISSUE THREAD

**Issue by SMRockend** [orizens/angular2-infinite-scroll#124]
I cannot get it work in webpack. No errors no scrolling. I was wondering if you could confirm supporting of webpack. Thank you .

**Comment by orizens** [comment]
sure - ng2-infinite-scroll is loaded successfully with webpack - have a look at my open source project-  Echoes Player (ng2 version) - http://github.com/orizens/echoes-ng2

in production - http://orizens.github.io/echoes-ng2
