### ISSUE TITLE
Adding only the new values to the HTML

### ISSUE THREAD

**Issue by inshaf** [orizens/angular2-infinite-scroll#129]
im new to Angular2, in your example, onScroll() method appends values to a array (push to array) and values of this array is looped and shown in the HTML. This means every time onScroll() trigger, the whole array is looping again and again to show in the HTML right ?

is it possible to get only the values from onScroll() and append to HTML. Without append to the array and looping it to generate HTML.

**Comment by orizens** [comment]
no - that's not correct.
Angular's change detection adds the new delta and **doesn't** render all the array items again.
