### ISSUE TITLE
Not working with angular-cli 1.0.0-beta.26

### ISSUE THREAD

**Issue by lucky-lou** [orizens/angular2-infinite-scroll#130]
Copied examples verbatim. Nothing.

**Comment by lucky-lou** [comment]
Also tried with angular-cli 1.0.0-rc.1 with no luck

**Comment by lucky-lou** [comment]
steps tried:

ng new infini-test
npm install npm install angular2-infinite-scroll --save
modify /src/app/app/module.ts to import InfiniteScrollModule and add InfiniteScrollModule to imports array.
add div with infinite-scroll attribute (Copy/ Paste from example) to app.component.html
add content to exceed the div's size to app.component.html
add the css to define height and set overflow to scroll app.component.css
add the onScroll() function to app.component.ts to console log when the scroll occurs to to app.component.ts

Nothing

**Comment by orizens** [comment]
hi @lucky-lou 
I'm in the process converting http://github.com/orizens/echoes-ng2 to use angular-cli.  
I got infinite-scroll working as expected with 1.0.0-rc.1.  
please update.
thanks.

**Comment by lucky-lou** [comment]
Can you provide code that you used to make this work. I've provided the steps I performed that don't work. The example you linked to is not an angular-cli project.

**Comment by orizens** [comment]
https://github.com/orizens/echoes-ng2/tree/ng-cli
