### ISSUE TITLE
Function gets trigger when scroll up

### ISSUE THREAD

**Issue by riyazbhanvadia** [orizens/angular2-infinite-scroll#133]
Hi,

First time when you scroll down function gets trigger properly, but once you reach bottom of scroll and then scroll up its again trigger function. 

Same problem exits in your http://echoesplayer.com  url also.

If you scroll down once and then you move scroll little up it trigger api.

**Comment by orizens** [comment]
that's reported as an issue at #128 .
I'm closing this one. please subscribe to #128
