### ISSUE TITLE
Getting Error 'Unexpected token <'

### ISSUE THREAD

**Issue by tony-lein** [orizens/angular2-infinite-scroll#134]
I added the npm and import { InfiniteScrollModule } from 'angular2-infinite-scroll'; to my module.

Page throws error when loading:

EXCEPTION: Uncaught (in promise): Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)

**Comment by orizens** [comment]
hi @tony-lein 
please consult the examples in the readme for how to load this module.

**Comment by tony-lein** [comment]
I assure you I did, I'm thinking there is a conflict with another module.

**Comment by orizens** [comment]
without an example, i cannot assist.

**Comment by tony-lein** [comment]
Sorry, I'm not sure how to give you an example since this is a small piece of an enterprise app.  I will see if I can delve down into the issue.

**Comment by orizens** [comment]
for further assistance, you can contact me privately at http://orizens.com/contact or register for a [consulting service here](https://docs.google.com/forms/d/e/1FAIpQLSc341_p9YiUeMHipBMDujCv0bHJfQD1NKWFvoYkcJiFeMm4Ig/viewform)

**Comment by kev23777** [comment]
@tlcoder Did you ever find a solution to the "Unexpected token <" error? I am facing the same issue.

**Comment by tlcoder** [comment]
Nope, what we've done to get around this is bring the css into the component until this get's resolved.

**Comment by kev23777** [comment]
Wow, thanks for the fast response. Sorry to hear that you didn't find a solution. I will keep looking myself and update here if and when I resolve the issue.

**Comment by kev23777** [comment]
Figured out that I needed to add something to our project.config.js file

      this.addPackageBundles({
        name: 'ngx-infinite-scroll',
        path: 'node_modules/ngx-infinite-scroll/bundles',
        packageMeta: {
          main: 'ngx-infinite-scroll.umd.js',
          defaultExtension: 'js'
        }
      });

Not sure if that helps you.

**Comment by tlcoder** [comment]
Thanks Kev!
