### ISSUE TITLE
Not working with children loaded module

### ISSUE THREAD

**Issue by rodrigopandini** [orizens/angular2-infinite-scroll#136]
Hi, I'm just trying to put the InfiniteScroll to work with a nested component, but I'm still do not have lucky. Not sure if is a problem with a nested module or something else.

The tree is like that:
- root
  - AppComponent
    - LayoutComponent
      - VideosComponent
        - VideoListComponent 

The router has the preloaded Video module
```typescript
...
const routerConfig: ExtraOptions = {
  preloadingStrategy: PreloadSelectedModulesOnly,
  useHash: false
};
export const routing = RouterModule.forRoot([{
    path: '',
    component: LayoutComponent,
    children: [
      {path: '', component: HomeComponent},
      {path: 'videos', loadChildren: 'app/videos/videos.module#VideosModule', data: {preload: true}}
    ]
  },
  {path: '**', component: ErrorComponent}
], routerConfig);
```
Bellow the `layout.component.html` (template for LayoutComponent):
```html
<mdl-layout mdl-layout-fixed-header>
  <mdl-layout-header>
    <mdl-layout-header-row>
      <mdl-layout-title>
        <a [routerLink]="['']" class="home-title">Test</a>
      </mdl-layout-title>
      <mdl-layout-spacer></mdl-layout-spacer>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <a class="mdl-navigation__link" [routerLink]="['/videos']">Videos</a>
      </nav>
    </mdl-layout-header-row>
  </mdl-layout-header>
  <mdl-layout-content 
     infinite-scroll
     [infiniteScrollDistance]="2"
     [infiniteScrollThrottle]="300"
     (scrolled)="onScroll()">
    <router-outlet></router-outlet>
  </mdl-layout-content>
</mdl-layout>
```
As far as I can inspect, the scroll that appears is related to the `mdl-layout-content` section.

The InfiniteScrollModule is imported in the app main module and inside the VideoListComponent I'm try to use the infinitescroll, but no events is triggered (the onScroll() function is never called). No errors occurs. I also tried to import the InfiniteScrollModule in the VideosModule, but not working.
Some advice?

**Comment by rodrigopandini** [comment]
OK. Now I got it.
I placed `[scrollWindow]="false"` in the `mdl-layout-content` to listen to local scroll, as I suspected.
I created a `ScrollContentService` to do the comunication between `LayoutComponent` and his "grandson" `VideoListComponent`. Not so pretty, but works :)

**Comment by sonnb** [comment]
How do the service work? I am facing the same issue but the [scrollWindow]="false" does not help.

**Comment by rodrigopandini** [comment]
Hi @sonnb, sorry for delay.

Here is my service:
```typescript
import { Injectable } from '@angular/core';
import { Subject } from 'rxjs/Subject';

@Injectable()
export class ScrollContentService {
  // Observable string sources
  private scrollAnnouncedSource  = new Subject<string>();
  // Observable string streams
  scrollAnnounced$ = this.scrollAnnouncedSource.asObservable();

  // Service message commands
  announceScroll(scroll: string) {
    this.scrollAnnouncedSource.next(scroll);
  }
}
```

In your html, use like this:
```html
<mdl-layout-content
        infinite-scroll
        [infiniteScrollDistance]="2"
        [infiniteScrollThrottle]="300"
        (scrolled)="onScroll()"
        [scrollWindow]="false">
  <router-outlet></router-outlet>
</mdl-layout-content>
```
In the associated component, you can inject the service like this:
```typescript
...
export class LayoutComponent {
  constructor (private scrollContentService: ScrollContentService) { }

  onScroll() {
    this.scrollContentService.announceScroll('scrolled');
  }
...
```
And then, in your children component, you can listen to your observable, like this:
```typescript
...
export class VideoListComponent implements OnInit, OnDestroy {
  subscription: Subscription;
  start: number = 0;
  
  constructor (private videoService: VideoService,  scrollContentService: ScrollContentService) {
    this.subscription = scrollContentService.scrollAnnounced$.subscribe(
      () => {
        this.start += 10;
        this.getVideos(this.start);
      }
    );
  }
...
```

**Comment by sonnb** [comment]
Thanks @rodrigopandini for sharing. My problem was the scrolling div is not the div that I am configuring the infinite scroll for.
