### ISSUE TITLE
Scroll down not firing on ctrl+end in Windows

### ISSUE THREAD

**Issue by SridharSathya** [orizens/angular2-infinite-scroll#138]
Hi Orizens,

This is related to issue #67. 
I am not sure whether the issue is resolved or not. But I am still facing the issue. 
When I give ctrl+end or when I scroll fast to down, scroll event is not triggered. And I have to scroll up slightly and then event is getting triggered. Kindly look into this.

**Comment by orizens** [comment]
@SridharSathya - yes that's the same as #67 - the issues has been reopened.
