### ISSUE TITLE
How to use the bundle ? Packages names not match

### ISSUE THREAD

**Issue by jcoqueret** [orizens/angular2-infinite-scroll#139]
Hi,

I'm looking for a solution to use the bundle.
I use the following configuration in SystemJS
```javascript
map: {
    'angular2-infinite-scroll': 'librairies:angular2-infinite-scroll/bundles/angular2-infinite-scroll.js'
}
```

The file is loaded correctly but it SystemJS still try to load the modules separetly whereas they are declared in the same file.
After analyse the bundle, modules are declared as "**src/xxx**" but are required as "**./src/xxx**". If I modify the bundle to make declarations and requirements match, everything load fine.

Is there a problem with the bundle ? Do I miss something ?

**Comment by orizens** [comment]
hi @jcoqueret 
i'm not using systemjs - so i can't tell you if that's the expected behavior.

**Comment by orizens** [comment]
please consult the plunkr example
https://plnkr.co/edit/DrEDetYnZkFxR7OWWrxS?p=preview
