### ISSUE TITLE
Differentiate between scroll up and scroll down

### ISSUE THREAD

**Issue by tallkid24** [orizens/angular2-infinite-scroll#19]
Sometimes might want the infinite scroll to load a certain way on scroll up vs. scroll down.

**Comment by orizens** [comment]
interesting feature request - as well as implementation.
lets see if there are more requests for this.

**Comment by ahall** [comment]
+1

**Comment by tallkid24** [comment]
@orizens I'm going to need to implement this either way soon. I could create a pull request once I complete it.

**Comment by orizens** [comment]
@tallkid24  sounds great

**Comment by tallkid24** [comment]
@orizens I'm getting a 403 trying to push to a remote branch. Do I have to be made a contributor?

**Comment by orizens** [comment]
@tallkid24 
you should fork this repo and open a pull request.

**Comment by tallkid24** [comment]
@orizens ahh thanks. Never done a PR before. There is one out there now.

**Comment by orizens** [comment]
closed with https://github.com/orizens/angular2-infinite-scroll/pull/22
