### ISSUE TITLE
Cannot read property 'query' of null

### ISSUE THREAD

**Issue by Hongbo-Miao** [orizens/angular2-infinite-scroll#28]
I got this error after updating from `0.1.2` to `0.1.3`.

> EXCEPTION: TypeError: Cannot read property 'query' of null

The code is quite simple:
```ts
import { Component } from '@angular/core';
import { bootstrap } from '@angular/platform-browser-dynamic';
import { InfiniteScroll } from 'angular2-infinite-scroll';

@Component({
  selector: 'app',
  directives: [InfiniteScroll],
  styles: [`
    .search-results {
      height: 20rem;
      overflow: scroll;
    }
  `],
  template: `
    Hello InfiniteScroll!
    <div class="search-results"
         infinite-scroll
         [infiniteScrollDistance]="2"
         [infiniteScrollThrottle]="500"
         (scrolled)="onScroll()">
      <p>1</p>
      <p>2</p>
      <p>3</p>
    </div>
  `
})
class App {
  onScroll () {
    console.log('scrolled!!')
  }
}
bootstrap(App);
```

It happens after I adding this part (Without this part, no error):
```
<div class="search-results"
    infinite-scroll
    [infiniteScrollDistance]="2"
    [infiniteScrollThrottle]="500"
    (scrolled)="onScroll()">
  <p>1</p>
  <p>2</p>
  <p>3</p>
</div>
```

**Comment by orizens** [comment]
hi @Hongbo-Miao 
need more info.
can you setup a plunkr that shows the issue?

**Comment by Hongbo-Miao** [comment]
The working 0.1.2 codes:
https://plnkr.co/edit/uof65imnVnMooMlBksoe?p=preview

Everything is same, only version changes to 0.1.3
https://plnkr.co/edit/qlqHhLHeO3DdTcdXiR10?p=preview

But the error shows (weird, different error, anyway, it has an error...):

> EXCEPTION: Can't resolve all parameters for InfiniteScroll: (?).

**Comment by orizens** [comment]
hi @Hongbo-Miao 
seems to be a bug...not sure about the root cause. do you have lead?

**Comment by Hongbo-Miao** [comment]
You mean lead for this bug? Nuh, I don't know how..

**Comment by marcalj** [comment]
Same as #30 
Very strange (using ng2 rc2)

**Comment by marcalj** [comment]
I think is this ```| any```:
https://github.com/orizens/angular2-infinite-scroll/blob/master/src/infinite-scroll.ts#L20

**Comment by orizens** [comment]
@marcalj "any" has been in 0.1.2 as well.

**Comment by tallkid24** [comment]
@orizens I think he is right though. I brought over the scroller files to my local, and removed the | any and it worked without any errors..

**Comment by orizens** [comment]
@tallkid24 can you share such an example that works?

**Comment by tallkid24** [comment]
@orizens unfortunately, no. Work code.

**Comment by orizens** [comment]
@tallkid24  @marcalj i have confirmed this - thanks!
a fix will be pushed soon.

**Comment by marcalj** [comment]
Fantastic, it works, thanks!
