### ISSUE TITLE
Cannot compile due to reference path

### ISSUE THREAD

**Issue by marcalj** [orizens/angular2-infinite-scroll#29]
Please remove ```/// <reference path="../typings/index.d.ts" />``` and add this file in the tsconfig.json file.

```
files: ["../typings/index.d.ts"]
```

Thanks!

**Comment by orizens** [comment]
hi @marcalj 
this file should be included in both tsconfig.json?

**Comment by orizens** [comment]
fixed with #35

**Comment by marcalj** [comment]
Brilliant! Thanks!
