### ISSUE TITLE
[infiniteScrollDistance] and (scrolled) do not work as expected

### ISSUE THREAD

**Issue by Hongbo-Miao** [orizens/angular2-infinite-scroll#31]
I am using angular2-infinite-scroll 0.1.2.

I expect
```ts
[infiniteScrollDistance]="2"
(scrolled)="onScrollDown()"
```
makes `onScrollDown()` runs only when scroll down near the bottom.

However, it runs no matter I scroll up or down, also no matter it is near the bottom or not.

Check the [my plunker](https://plnkr.co/edit/WCbw5EwH6RA5SMhtUkzr?p=preview).
Am I using it wrong? Thanks

**Comment by tallkid24** [comment]
I think you'll have to change the infiniteScrollDistance. I use 0.8 and thats about 75% down the page. As for the scroll up/down, in 0.1.3 they are differentiated.

**Comment by Hongbo-Miao** [comment]
@tallkid24 I tried to changed to 0.8, but it is still same..
https://plnkr.co/edit/NKRA5scV6g0TTVH29BQz?p=preview

**Comment by Hongbo-Miao** [comment]
Thanks @tallkid24. Both of these already updated angular2-infinite-scroll 0.1.4.

[This](https://plnkr.co/edit/RYyhsl3ERowQ4nPKVnER?p=preview) uses `[infiniteScrollDistance]="2"`
[This](https://plnkr.co/edit/VT3gTobWJjpODpKPSiqv?p=preview) uses `[infiniteScrollDistance]="0.8"`

Right now both of them only run `onScrollDown()` one time in the beginning when you scroll.
But still how can I run `onScrollDown()` only when scroll down near the bottom?

**Comment by Hongbo-Miao** [comment]
Hi @orizens , would you mind adding a working simple plunker demo in the readme file? So people can start quickly

**Comment by orizens** [comment]
@Hongbo-Miao 
you should use this style:
```css
.search-results {
      height: 100%;
      overflow: scroll;
    }
```
since the way you constructed the directive is to listen to the window scroll and the the actual div. 
if you want it to scroll relatively to the div, you should set ```[scrollWindow]="false"```

**Comment by orizens** [comment]
@Hongbo-Miao 
i forked your plunkr and added to the demo.
thanks.

**Comment by orizens** [comment]
@Hongbo-Miao also,
I see an issue where the immediate scroll, scroll in the beginning. 
I think that the issue that you describe should be in defined in a new issue thread.

**Comment by Hongbo-Miao** [comment]
@orizens thanks! That is awesome!
That "issue" is because of I set `immediateCheck` to true I guess..

**Comment by orizens** [comment]
great. 
ok. i'll update the examples and docs for this as well. 
Thanks!

**Comment by fereshenteti** [comment]
Hello, 
I think I have found a little workaround that fixes this issue by setting the infiniteScrollThrottle to 0, and make your own throttling method.

So here's how I did it:

in the HTML side, use these attributes:

```
[infiniteScrollThrottle]="0"
(scrolled)="loadMore()"
```

on the other hand, in the ts file, make your own throttling condition in the loadMore() function:

```
loading = false;
loadingThrottle = 300;

loadMore() {
    if (!this.loading) {
      this.loading = true;

      window.setTimeout(() => {

        // your loading logic here..

        this.loading = false;
      }, this.loadingThrottle);
   }
}

```

Hope this helps.
