### ISSUE TITLE
infiniteScrollUpDistance is not working

### ISSUE THREAD

**Issue by marcgr** [orizens/angular2-infinite-scroll#32]
I am getting this error when I include it as in the example.

_Template parse errors:
Can't bind to 'infiniteScrollUpDistance' since it isn't a known native property_ 

The (scrolledUp) event is not triggering either with or without including the infiniteScrollUpDistance attribute.  

I can get the default (scolled) event to work as expected, just not the scroll up.

**Comment by tallkid24** [comment]
What version are you using?

**Comment by marcgr** [comment]
0.1.2 

I tried to upgrade to 0.1.3 and I got the typings duplicate warnings (added as another issue) and a dep not found error, so had to switch back to 0.1.2.

**Comment by tallkid24** [comment]
0.1.3 is the one with the scroll up stuff, but there is a bug right now with that version I think.

**Comment by marcgr** [comment]
Just upgraded to the 0.1.4 and all is working well now!  Thanks

**Comment by orizens** [comment]
thanks for cofirming that
fix is on #35
