### ISSUE TITLE
Can we get single file with all contents

### ISSUE THREAD

**Issue by golear91** [orizens/angular2-infinite-scroll#36]
I am writing chrome extension, so i'm trying to keep footprint as small as possible. Currently need to include multiple js files, can we get a single umd to include instead of the multiple for this directive?

**Comment by orizens** [comment]
hi @golear91 
the bundle includes all files - https://github.com/orizens/angular2-infinite-scroll/blob/master/bundles/angular2-infinite-scroll.js. 
however, if you use typescript for the chrome extension - you can use webpack or browserify to bundle all js files anyways into one file.

**Comment by golear91** [comment]
When I try to load from that file I get the following error:
![image](https://cloud.githubusercontent.com/assets/16123225/16163302/585d1806-348d-11e6-9a5e-ad78a46a670d.png)

I changed systemjs packages config from `'angular2-infinite-scroll': { main: 'angular2-infinite-scroll.js', defaultExtension: 'js' }` to `'angular2-infinite-scroll': { main: 'bundles/angular2-infinite-scroll.js', defaultExtension: 'js' }`

and it goes from working correctly to that error above.

**Comment by orizens** [comment]
hi.
I'm not sure of how to use the bundle.

**Comment by orizens** [comment]
hi @golear91 
this has been resolved, isn't it?

**Comment by orizens** [comment]
a umd version is available via npm package.
