### ISSUE TITLE
How can i destroy this directive when we reach to last page?

### ISSUE THREAD

**Issue by ngonam22** [orizens/angular2-infinite-scroll#39]
When we scroll (go) to the last page, we want to the destroy infinite scroll directive so that it cant make any wasted requests repeatedly. 
I saw you already attached it with ngOnDestroy life circle hook, but i dont know how to call this event.
Thank you.

**Comment by orizens** [comment]
hi. 
this behavior is logic. the decision to make requests is dependent on the logics rathe than the directive.

**Comment by ngonam22** [comment]
Hi @orizens ,
But is there anyway to destroy the directive completely without performing any unnecessary logic? 
Thank you

**Comment by orizens** [comment]
currently - no. 
however, i'm working on converting the 'Scroller.ts' to an injected service - so perhaps - through that - you'll be able to stop the scroller's listener.

**Comment by orizens** [comment]
hi.
you can use "scroller.clean()".
