### ISSUE TITLE
Not implement in Inner Div scroll

### ISSUE THREAD

**Issue by muhammadadnan97** [orizens/angular2-infinite-scroll#4]
when i am apply to implement in inner div scroll its not working

**Comment by orizens** [comment]
hi.
currently, it applies to scrolling in the body only.

**Comment by muhammadadnan97** [comment]
i implemented on the dive i will share code with you thanks

**Comment by orizens** [comment]
great.
thanks.

**Comment by Flea505** [comment]
@muhammadadnan97 Hi there, can you share how you implemented the infinite scroll on a div instead of the entire body?

**Comment by muhammadadnan97** [comment]
@Flea505  give me the email address i will send u the code

**Comment by Flea505** [comment]
Awesome! You can send here to felicia.chavez.5@gmail.com
Thank you.

Felicia Chavez
e: felicia.chavez.5@gmail.com
t: (505)-401-4415

**Comment by muhammadadnan97** [comment]
check Your mail.

**Comment by fredgate** [comment]
I have the same problem. The directive listen scroll events of the window, not of the element to which it is attached. SO this is not not very useful.
@muhammadadnan97 Could you submit your code as a pull request. Some members will do a code review, and when it is ok @orizens will merge. Thanks.

**Comment by eloquent0** [comment]
@muhammadadnan97 Hi , can you plz share how you implemented the infinite scroll on a div instead of the entire body?

**Comment by paulosoaresvieira** [comment]
i need something like this too, @muhammadadnan97 can you please share with us?
thanks!

**Comment by MikeSaprykin** [comment]
i need something like also, @muhammadadnan97 . Could you please show the code?

**Comment by orizens** [comment]
this should be release in the next release soon.
