### ISSUE TITLE
Bad perfomance - runs change detection cycle continually 

### ISSUE THREAD

**Issue by nesterua** [orizens/angular2-infinite-scroll#40]
Take live example , implement DoCheck for App component. Write something to console from it.

Open console. You will see that change detection cycle runs continually.

Leave browser for some time. It will crash.

**Comment by galsch** [comment]
I'm running into same issue. What's going on here?

**Comment by orizens** [comment]
hi @nesterua 
the live demo logs to the console "scrolled!!" but it don't see it continuously logs. 
can you supply a plunkr?

**Comment by nesterua** [comment]
Here https://plnkr.co/edit/MQyaJOOuKVxjruQU861C?p=preview
open preview in separate window  and look to console  for message "change detection cycle!" It fire continually. After scroll event it stops.

**Comment by orizens** [comment]
@nesterua 
I can see the logs now. 
however, by using ngDoCheck, it means that you need to implement a change detection strategy rather the angular's built in one. I'm not sure why this happens or whether it should run continuously. 
By reading thru the [ngDoCheck docs](https://angular.io/docs/ts/latest/api/core/index/DoCheck-class.html) , it seems this hook should be implemented in nested components with at least 1 "@Input" rather than the main app.

**Comment by galsch** [comment]
Hi Oren,

I forked @nesterua example showing the problem without ngDoCheck:

https://plnkr.co/edit/0lItGxrWqvf2JbXirCK6?p=info

Please take a look. 

Thanks

**Comment by orizens** [comment]
@galsch 
Thanks for your example. 
I've found out that if you use "enableProdMode()", it somehow still calls the "testMethod" (because it needs to evaluate this expression) but stops whenever there is no scroll. 
so - it's either an angular2 framework thing or something inside this directive.

**Comment by galsch** [comment]
Thanks @Oren for the quick response!

I believe this is a bug in the directive - a critical bug IMO as on mobile devices this makes the user experience very laggy.

Please try to fix this bug as this library is extremely important for all Angular2 users :-)

Thanks!

**Comment by orizens** [comment]
@galsch Thanks :)
A possible cause that i noticed is the use of ["setInterval"](https://github.com/orizens/angular2-infinite-scroll/blob/master/src/scroller.ts#L51) in scroller.ts.

**Comment by galsch** [comment]
@orizens I see bug is fixed - awesome!

Please update once there is a new version in npm :-)

**Comment by justme1** [comment]
@orizens will there be a new npm version? Latest version doesn't include this important fix.

**Comment by orizens** [comment]
hi all.
i published version 1.5 with this bug fix.

Thanks.

**Comment by galsch** [comment]
@orizens thank you very much for the update!

This actually fixed the endless change detection when app is in idle. However, still when we scroll the change detection is running - why is that?

Update fork example in plunkr with 1.0.5:

https://plnkr.co/edit/k8UZ9UBp26jU3zGDwmo9?p=preview
