### ISSUE TITLE
I created a PR with simple Horizontal Scrolling

### ISSUE THREAD

**Issue by emeyekayee** [orizens/angular2-infinite-scroll#43]
Take a look if you're interested and LMK

**Comment by orizens** [comment]
@emeyekayee Thanks!
I'll look into it. 
This is indeed - a useful feature.

**Comment by jlsuarezs** [comment]
Is it ready to use? :D

**Comment by orizens** [comment]
@jlsuarezs - Thanks to @emeyekayee  - it is now.
