### ISSUE TITLE
Updating to latest version caused my build to fail.

### ISSUE THREAD

**Issue by golear91** [orizens/angular2-infinite-scroll#46]
I started with version 0.1.4. There is a file, `angular2-infinite-scroll.js` in this distribution which I point systemJS to during config.  When I updated to latest version of infinite-scrolling module, this file disappeared (replaced by .ts file), and caused the typescript compilation step of my build to fail. I couldn't get systemJS to load from the new .ts file easily so I reverted to the old version.

**Comment by orizens** [comment]
v0.1.8 fixed by 7b64910718ea0206b845114f13902136474a0221
for future reference: 
new files should be added to both tsconfig.json
