### ISSUE TITLE
System is not defined using 0.1.7 and angular webpack starter

### ISSUE THREAD

**Issue by ahuwaa** [orizens/angular2-infinite-scroll#47]
This module is great! Thanks for working on it. I can't seem to use this with webpack due to the src dependencies on System and lack of the angular2-infinite-scroll.ts file in the project root.

Can someone please explain why
1. 0.1.7 is available in npm but not shown in the github repo here
2. 0.1.6 is not installable via npm
3. the .ts file in root was removed

Thanks

**Comment by orizens** [comment]
thanks.
there's a bug on that #46

**Comment by orizens** [comment]
v0.1.8 fixed by 7b64910718ea0206b845114f13902136474a0221
for future reference: 
new files should be added to both tsconfig.json

**Comment by ahuwaa** [comment]
thanks :) much appreciated

**Comment by orizens** [comment]
thanks for reporting :)
