### ISSUE TITLE
Unable to install it on Angular 2 RC4

### ISSUE THREAD

**Issue by BenoitBruy** [orizens/angular2-infinite-scroll#53]
Hello,

I'm interesting to your infinite scroll for Angular 2 but I'm unable to install it..

In my angular-cli-build.js, I write:

`'angular2-infinite-scroll/bundles/angular2-infinite-scroll'`

In system-config.ts, I write:

in map section: `'angular2-infinite-scroll'` : `'vendor/angular2-infinite-scroll/bundles/angular2-infninte-scroll.js'`

And finally in package section:

`angular2-infinite-scroll': {
   format: global
}``

**Comment by orizens** [comment]
hi @BenoitBruy 
please consult this in the wiki - https://github.com/orizens/angular2-infinite-scroll/wiki/Tips

let me know if this solves the issue. 
thanks.

**Comment by BenoitBruy** [comment]
It doesn't solve.. I followed exaclty what is written but that is the message I've got: 

`GET http://localhost:4200/vendor/angular2-infinite-scroll/index.js 404 (Not Found)`

**Comment by BenoitBruy** [comment]
In fact, it's work :)
