### ISSUE TITLE
(scrolled)="onScrollDown()" getting called multiple times

### ISSUE THREAD

**Issue by dheeraja00** [orizens/angular2-infinite-scroll#56]
I have this code:
```
<table class="table table-striped table-hover inline-edit"
	infinite-scroll
	[infiniteScrollDistance]="2"
	[infiniteScrollThrottle]="10"
	(scrolled)="onScrollDown()">
```
```
onScrollDown() {
      this.pageNumber += 1;
      this.getContacts();
}
```

When it reaches viewports length it calls onScrollDown multiple times like 5/6 times

**Comment by zoehneto** [comment]
Have you tried increasing the throttle? You have currently set it to 10 milli seconds which might be the issue. A number between 300 and 600 milli seconds typically prevents this kind of issue.

**Comment by dheeraja00** [comment]
Well yeah increasing throttle helps but I don't want user to wait for loading, it should be like instant, so how that can be done?

**Comment by zoehneto** [comment]
It would still be instant for the first event, the throttle only drops the events after the first one within the configured amount of time.

**Comment by zoehneto** [comment]
You were right about the throttle behavior, the behavior I described only existed in a previous version. PR #58 restores this behavior and should make the scrolling more responsive.

**Comment by igordeoliveirasa** [comment]
Here it's getting called multiple times too.
