### ISSUE TITLE
ScrollDown Event fired on Scroll Up

### ISSUE THREAD

**Issue by zeeshanjan82** [orizens/angular2-infinite-scroll#57]
I am facing a very strange issue, my HTML code looks like this
```
<li class="list-group-item" 
*ngFor="let promoter of Promoters | async" 
infinite-scroll  
[infiniteScrollDistance]="10" 
[infiniteScrollThrottle]="500"  
(scrolled)="onScrollDown()">
</li>
```
In this case my onScrollDown() funtion is getting called even when I scroll up.

**Comment by orizens** [comment]
hi @zeeshanjan82 .
please consult the example in the readme - https://github.com/orizens/angular2-infinite-scroll/blob/master/README.md
your code attach an event handler for each "li" element.

**Comment by orizens** [comment]
@zeeshanjan82 
have you solved the issue?
if so, please mark it as closed. 
Thanks.

**Comment by peterhoang** [comment]
I'm also experience the same thing. I do not want scroll up to trigger my scrolled down handler.

```
<div infinite-scroll
     [infiniteScrollDistance]="10"
     [infiniteScrollThrottle]="500"
     (scrolled)="onScrollDown()">

     <ul>...</ul>
</div>
```

**Comment by orizens** [comment]
@peterhoang 
notice that the container should have a fixed height as shown in the demo plunkr:
https://plnkr.co/edit/DrEDetYnZkFxR7OWWrxS?p=preview
since height is the page's height, this is why the scrolled trigger is very sensitive and triggered almost immediately.

**Comment by Joqus** [comment]
The example also have a strange behaviour. If I go down quickly the scroll event is not fired. But when I go up a little it is called. 

Something weird seems to be happening here.

**Comment by orizens** [comment]
hi @Joqus 
i noticed that. currently, i don't know why it happens. 
perhaps - I should consider checking with a timeout if the handler suppose to trigger a scroll event.

**Comment by thohoh** [comment]
Same to me. Have you figured why is this happening?

**Comment by sollabeck** [comment]
also experiencing simliar issue. would like to find a fix for scrolling down too quickly

**Comment by orizens** [comment]
this seems to occur because of the issue described in #67
