### ISSUE TITLE
suggestion: 'Invalid Calling Object' error in IE11 on "toString.call" method fix 

### ISSUE THREAD

**Issue by tulitheprogrammer** [orizens/angular2-infinite-scroll#61]
I fixed it locally bt replacing these lines in the scroller contructor:
        //this.isContainerWindow = toString.call(this.windowElement).includes('Window');
        this.isContainerWindow = Object.prototype.toString.call(this.windowElement).includes('Window');

**Comment by ionutghica89** [comment]
Hello, 
I can confirm that by replacing  the line in the constructor of the scroller.js fixed the issue on IE 11.
Looking forward for the fix/addition as, because we are using CI and Automation to deploy, it's not really viable to edit the node package .
Best regards,
Ionut
