### ISSUE TITLE
RC-5 is out

### ISSUE THREAD

**Issue by dheeraja00** [orizens/angular2-infinite-scroll#63]
RC-5 is out, so can you please update this to rc-5, it will be great that way..

**Comment by orizens** [comment]
hi.
currently, it is updated to rc4 - and it should work out of the box with rc5. 
However, this is considered.

**Comment by tamarshore** [comment]
+1

**Comment by orizens** [comment]
released and closed with 2d784323640063da9d0ea33a3f56b4c016269a77
