### ISSUE TITLE
Reloading trusted HTML on scroll

### ISSUE THREAD

**Issue by jylinman** [orizens/angular2-infinite-scroll#68]
I am trying to embed some HTML that I know is trusted (from oembeds) and use them in a loop.  They display fine, but whenever I go to scroll (by even a pixel) it reloads all the iframes on the page.  You can see this happening in this plunker:

https://plnkr.co/edit/qklbNzvDSOzoI2t0K7fA?p=preview

**Comment by orizens** [comment]
hi. 
this is DOM behavior - here's a related description - http://stackoverflow.com/questions/14864821/jquery-ui-effect-causes-iframe-reload
