### ISSUE TITLE
Not working on modal

### ISSUE THREAD

**Issue by Perezmarc** [orizens/angular2-infinite-scroll#71]
I created a modal, position fixed, and I'm blocking the scroll of its background content, the html tag, with overflow: hidden. 
`<div  class="modal content-wrapper">
  <div
       infinite-scroll
       [infiniteScrollDistance]="2"
       [infiniteScrollThrottle]="500"
       (scrolled)="onScroll()"
       [scrollWindow]="false">
      <app-picture [item]="post"  [cindex]="i"  *ngFor="let post of posts"></app-picture>
    <my-spinner [isRunning]="isRequesting"></my-spinner>
  </div>
</div>`

the scroll itself, the function of the browser, its working properly, but the onScroll() function is never called :S

-RC4
Thanks!

**Comment by orizens** [comment]
hi.
can you share a plunkr?

**Comment by Perezmarc** [comment]
something like this:
https://plnkr.co/edit/exNMyAtVYnCfH3qXxzVB?p=preview

I want to scroll content-wrapper

**Comment by orizens** [comment]
this plunkr doesn't include infinite-scroll

**Comment by orizens** [comment]
hi @Perezmarc 
here's a rough example of you would use infinite scroll with a modal (styled with bootstrap) 
https://plnkr.co/edit/QnQOwE9SEapwJCCFII3L?p=preview
