### ISSUE TITLE
Release 1.2.0 throws compiler error with typescript < 2.0.0

### ISSUE THREAD

**Issue by zoehneto** [orizens/angular2-infinite-scroll#72]
Since the 1.2.0 release is built with typescript 2.0.0 the file `scroller.d.ts` containes the reference to `@types` typings which don't work with the current stable release of typescript (1.8.x) and throw a compiler error.

**Comment by orizens** [comment]
perhaps there's a flag that can suppress these errors?

**Comment by zoehneto** [comment]
I don't think that is possible. The issue is created by the line `/// <reference types="core-js" />` which creates a syntax error with typescript 1.8 because `@types` only works with typescript >= 2.0. I have created a PR which changes the compiler options to prevent the reference from being included in the output.

**Comment by orizens** [comment]
@zoehneto 
since i consider myself and others who are using Typescript 2, can you suggest a strategy to allow sing typescript 1.8 and typescript 2 as well?

**Comment by zoehneto** [comment]
PR #73 should work for both TypeScript 1.8 and 2.0 by replacing the core-js dependency with the built-in typings for compilation, allowing everyone to use their preferred polyfill at runtime (or skipping it completely).

**Comment by orizens** [comment]
thanks
