### ISSUE TITLE
Cannot find type definition file for 'core-js'.

### ISSUE THREAD

**Issue by Hongbo-Miao** [orizens/angular2-infinite-scroll#74]
I am using Angular 2 RC 4, TypeScript 2.
After updating from angular2-infinite-scroll **0.1.95** to **0.2.0**, got the error in my terminal:

> ERROR in /my-project/node_modules/angular2-infinite-scroll/src/scroller.d.ts
>     (1,1): error TS2688: Cannot find type definition file for 'core-js'.

which is this line in the scroller.d.ts file gives error:
`/// <reference types="core-js" />`

**Comment by zoehneto** [comment]
This issue comes from using TypeScript 1.8, see issue #72

**Comment by Hongbo-Miao** [comment]
@zoehneto thank, I saw that, but I am using TypeScript 2

**Comment by zoehneto** [comment]
In that case installing `@types/core-js` and adding it to your tsconfig file should fix it

**Comment by zoehneto** [comment]
Either way the issue should be resolved if my PR is merged, since core-js is only needed to polyfill es6 functionality and should not be a hard dependency.

**Comment by Hongbo-Miao** [comment]
Yeah, I tried that too..
After `npm install @types/core-js`,it gives me unlimited error in the terminal:
The log is here http://paste.ofcode.org/NrRFrJxxTPXVcdeZThLEpT

**Comment by orizens** [comment]
@Hongbo-Miao 
I suggest to clean any "typings" folder is exist and other cache directories - even ```npm i``` everything at the moment.

**Comment by zoehneto** [comment]
That typically happens if you have the same typings installed using the typings program (in the typings folder) or if you have added es6 as lib in your tsconfig file.

**Comment by orizens** [comment]
@Hongbo-Miao 
please notice that v0.2 is dependent on Rc.5

**Comment by Hongbo-Miao** [comment]
oh thanks, just notice it is a hard dependency on angular 2 rc5!

**Comment by AhsanAyaz** [comment]
@Hongbo-Miao did you solve this issue?

**Comment by Hongbo-Miao** [comment]
@AhsanAyaz yeah, just updated to Angular 2 final, and works well
