### ISSUE TITLE
Cant find InfiniteScrollModule

### ISSUE THREAD

**Issue by Perezmarc** [orizens/angular2-infinite-scroll#75]
Hi, I'm trying to use it on ngModule, and in your documentation you import it as:
 import { InfiniteScrollModule } from 'angular2-infinite-scroll';

But in 0.2.1 cannot resolve.

**Comment by orizens** [comment]
probably a problem with your setup? 
the latest example with the modal works with v0.2.1
https://plnkr.co/edit/QnQOwE9SEapwJCCFII3L?p=preview
