### ISSUE TITLE
Broken on Chrome and Chromium

### ISSUE THREAD

**Issue by Caballerog** [orizens/angular2-infinite-scroll#78]
I've been testing the module in Linux/Chrome and Linux/Chromium which doesn't work. 

Although, I've tested using Linux/Firefox and this works.

Chrome: Versión 46.0.2490.86 
Chromium:48.0.2564.116 

I think that is a bug (my browsers version are less 1 year) because there are a lot of old browsers.

**Comment by Caballerog** [comment]
I've upgrade my browsers and the module works.

**Comment by orizens** [comment]
hi @Caballerog 
you reopened the issue. does the problem still happen?
can you share a plunkr?

**Comment by JordanFriendshuh** [comment]
Your example plunkr is broken on older chrome versions.  I was on chrome vs 48 and it was broken.

**Comment by Caballerog** [comment]
Hi @orizens the problem is explain for @JordanFriendshuh.

**Comment by orizens** [comment]
I'm but confused.
the bug exists in older stable chrome versions than v53?

**Comment by Caballerog** [comment]
@orizens  Yes, I've tested in 

Chrome: Versión 46.0.2490.86 
Chromium:48.0.2564.116

**Comment by orizens** [comment]
can you suggest a way to check this on these versions?

**Comment by Caballerog** [comment]
@orizens I've find a repository with google chrome Version 48: http://www.slimjet.com/chrome/google-chrome-old-version.php

Also there is this web service: https://www.browserling.com/browse/win/vista/chrome/48/https%3A%2F%2Fplnkr.co%2Fedit%2FDrEDetYnZkFxR7OWWrxS%3Fp%3Dpreview

**Comment by orizens** [comment]
that's a bit problematic.
I think we need to rely on newer versions.
