### ISSUE TITLE
Breaking karma tests

### ISSUE THREAD

**Issue by jimmythesaint82** [orizens/angular2-infinite-scroll#79]
Get this on any test that touches infinitescroll

Cannot read property 'clean' of undefined

have fixed with a quick if statement

if(this && this.clean)
        this.clean();

&& 

  if(this.scroller)
            this.scroller.clean();

**Comment by orizens** [comment]
Hi.
Can you share an example?

**Comment by orizens** [comment]
this relates to PR #69 .
however, a different solution needs to be created.

**Comment by pbecotte** [comment]
I thought I had this problem, I was seeing that error message in my tests.

Turned out that my tests were blowing up in the 'BeforeEach' method (I was accessing an uninitialized variable).  Once I fixed THAT problem, THIS problem went away.

**Comment by orizens** [comment]
already fixed.
