### ISSUE TITLE
Add dependency on typings

### ISSUE THREAD

**Issue by stalniy** [orizens/angular2-infinite-scroll#80]
I don't use typescript and when I try to install your lib npm says:

sh: typings: command not found

**Comment by orizens** [comment]
hi. have run ```npm install``?

**Comment by stalniy** [comment]
looks like it's fixed in the master, but I use angular2.rc-4 that's why I need older version. Will try to find out a solution

**Comment by stalniy** [comment]
I run `npm i angular2-infinite-scroll@0.1.95`

**Comment by stalniy** [comment]
` npm -v
3.9.3`
