### ISSUE TITLE
Callback on (scrolled) gone wrong.

### ISSUE THREAD

**Issue by thohoh** [orizens/angular2-infinite-scroll#86]
'scrolled' callback called only when document is scrolled down, not a container the directive attached to.

```
<style>
     .items { height: 400px; overflowY: auto; }
</style>

 <div class="items"
         infinite-scroll
         [infiniteScrollDistance]="2"
         [infiniteScrollThrottle]="600"
         (scrolled)="onScrollDown()">
</div>
```

**Comment by orizens** [comment]
hi @thohoh 
that's the default design.
if you want the scroll to react by its container - use "[scrollWindow]=false".

**Comment by orizens** [comment]
documented in readme - https://github.com/orizens/angular2-infinite-scroll#behavior
