### ISSUE TITLE
Trigger constantly firing.

### ISSUE THREAD

**Issue by sunshineo** [orizens/angular2-infinite-scroll#87]
I feel there is something wrong with the number calculation. I scroll even a little bit, way far away from the bottom, I got multiple triggers.
![trigger](https://cloud.githubusercontent.com/assets/1072766/19107516/7925d2fc-8aa1-11e6-911e-b8b72049062b.jpg)

My html

```
<md-input (keyup)="emitInput($event)" placeholder="Search nearby restaurants" style="width:100%"></md-input>
<h2 *ngIf="showLoading">Loading ...</h2>
<div infinite-scroll [infiniteScrollDistance]="1" [infiniteScrollThrottle]="500" (scrolled)="onScroll()">
    <md-card *ngFor="let restaurant of restaurants" flex-gt-md="45" flex-md="100" flex-sm="100" flex-xs="100" (click)="gotoDetail(restaurant)">
        <restaurant-card [restaurant]="restaurant"></restaurant-card>
    </md-card>
</div>
```

**Comment by orizens** [comment]
hi @sunshineo 
the current implementation does trigger the "onscroll" on the first scrolling - which should not happen. 
I'll have to take a look into that.

**Comment by sunshineo** [comment]
Your remaining is negative when scroll down and you have the code
```
var shouldScroll = remaining <= containerBreakpoint;
```
So it always fires
![remaining](https://cloud.githubusercontent.com/assets/1072766/19107822/f3238436-8aa2-11e6-919a-59973033d1f5.jpg)

**Comment by sunshineo** [comment]
Another number I feel does not make sense is
```
var scrolledUntilNow = height + this.pageYOffset(this.documentElement);
```
Should the height be there?

**Comment by orizens** [comment]
@sunshineo 
yes - the height value is crucial for calculating the total px that have been scrolled from the point zero of the document.

**Comment by orizens** [comment]
regarding your comment with the screenshot - 
if the content is that should be added to the container is loaded async via an http call - than you should implement the logics of what is should do - the event of "scrolled" should still be invoked if's in the right point.

**Comment by sunshineo** [comment]
@orizens I do not understand. I have always been using ajax load for my content and when I use angular2 beta, rc with 0.1.95 of this project, everything worked as expected. But now I upgrade to angular2 offical 2.0.1 and 0.2.2 of this project, I got this problem.

**Comment by orizens** [comment]
if you can supply an example of the problem in a plunker - that will help.

**Comment by iherbivore** [comment]
I'm not sure if this is OP's problem, but here is a scenario that gets me with this behavior: 

1. A scroll event is triggered
2. I fire ajax request for more.
3. The infiniteScrollThrottle expires before my new data is rendered
4. Loopback to step 1 because the div has not increased in length yet

**Comment by sunshineo** [comment]
@iherbivore Thanks. But that does not seems to be my problem.

**Comment by orizens** [comment]
to sum up: this logics should be handled outside the of this directive.

**Comment by sunshineo** [comment]
@orizens What do you mean by "outside the of this directive"??

**Comment by ivaanrl** [comment]
Did anyone find a solution to this?
