### ISSUE TITLE
Scroll inside div with overflow:scroll not firing

### ISSUE THREAD

**Issue by TSGames** [orizens/angular2-infinite-scroll#88]
When using infinite-scroll it's just firing when the body has scrolled, but not the actual div which is inside the body and may contains the infinite list.

Is it possible to select the element id which the infinite scroll listener should watch for?
```
<style>
.list{
  overflow-x: hidden;
  overflow-y: scroll;
  height:90%;
}
</style>
<div class="list">
  <div infinite-scroll (scrolled)="scroll()" *ngFor="let a of b">
     <!-- ... -->
    </div>
</div>
```

**Comment by orizens** [comment]
hi.
please read the [docs](https://github.com/orizens/angular2-infinite-scroll#behavior)

**Comment by TSGames** [comment]
Damn, I'm so sorry, completely missed the scrollWindow attribute, thanks a lot, sorry!

**Comment by TSGames** [comment]
After adding the attribute and set it to false, the event isn't firing anymore although I scroll inside the actual element.

**Comment by orizens** [comment]
look at this example - the modal window implements what you try to achieve
https://plnkr.co/edit/QnQOwE9SEapwJCCFII3L?p=preview

**Comment by TSGames** [comment]
I see. My issue was that I've attached the *ngFor list directly on the infinite-scroll item which doesn't work in this case.
