### ISSUE TITLE
Scrolling too quickly causes scroller handler not to fire

### ISSUE THREAD

**Issue by sollabeck** [orizens/angular2-infinite-scroll#90]
This is an issue that references an issue that is brought up in Issue #57. When I scroll down too quickly, it seems like the scroller handler isn't firing so I'm stuck at the bottom even though there are more records to load. If I scroll up a little bit it seems to run the handler and continue the scrolling accordingly.

**Comment by robw00t** [comment]
I see the same thing. Scroll super fast & grid stops at 99 in demo: https://plnkr.co/edit/DrEDetYnZkFxR7OWWrxS?p=preview. Scroll back up a bit then scroll down slowly & grid continues to load more rows.

**Comment by orizens** [comment]
hi @sollabeck 
thanks for reporting it.
I suspect it's the same bug as in #67 and a fix for this issue will solve both.

**Comment by orizens** [comment]
this seems to occur because of the same problem described in #67
