### ISSUE TITLE
not working in combination with perfect-scrollbar

### ISSUE THREAD

**Issue by lghinet** [orizens/angular2-infinite-scroll#93]
i`am trying to make it work with 
[https://github.com/zefoy/angular2-perfect-scrollbar](url)

but no success, 
`
<perfect-scrollbar class="full-width"
                   infinite-scroll 
                    [infiniteScrollDistance]="1"
                    (scrolled)="onScroll()"
                   [scrollWindow]="false"
                   >
....

</perfect-scrollbar>`

**Comment by orizens** [comment]
hi.
by the implementation, i can see that perhaps perfect scrollbar manipulates the scroll event - and perhaps over-riding the default.

**Comment by orizens** [comment]
closing this as its out of scope for this directive.
