### ISSUE TITLE
Could this package be used as a scroll glue?

### ISSUE THREAD

**Issue by donjae** [orizens/angular2-infinite-scroll#94]
Hi,

Could this module be used to be a scroll glue, to position the scroll view to the bottom to the page for new elements? 

If so, any ideas on how would I approach implementing it?

**Comment by orizens** [comment]
hi.
can you share an example of what you're trying to achieve?

**Comment by donjae** [comment]
I figured out how to do it via dom/elementref, but was wondering if perhaps this package had an api I could use. 

So imagine if list items we being pushed to the infinite scroll window, the window would automatically position it [close] to the last item in view.
