### ISSUE TITLE
Can we get a changelog?

### ISSUE THREAD

**Issue by tallkid24** [orizens/angular2-infinite-scroll#96]
I'm on infinite scroll 0.2.2 but not sure what changed from that version to 0.2.6. Would you be able to fill me in on what changed and also possibly create a changelog going forward?

**Comment by orizens** [comment]
hi @tallkid24 
currently, the commit history functions as the change log.
is there a procedure you're familiar with that can assist in creating a change log?

**Comment by tallkid24** [comment]
Yeah. It would just be manually updating a CHANGELOG.md file every release with what would be included in that release (see Angular2's https://github.com/angular/angular/blob/master/CHANGELOG.md). It's just an easier way for users to quickly look at the repo and check the changelog to see if there are any changes that they can take advantage of or see if something is breaking.

**Comment by orizens** [comment]
@tallkid24 
looks nice.
I will try in next releases to create a proper changelog.
thanks.

**Comment by orizens** [comment]
@tallkid24  granted :)
b5130dba68decfecd289b47fc6333ba9c583ac98 closes #96
https://github.com/orizens/angular2-infinite-scroll/blob/master/CHANGELOG.md

thanks for suggesting.

**Comment by tallkid24** [comment]
@orizens Thanks!
